//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelTracking.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlar
    {
        public int id { get; set; }
        public string Value { get; set; }
        public Nullable<bool> Key { get; set; }
        public Nullable<System.TimeSpan> Saats { get; set; }
    }
}
