//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelTracking.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hareketler
    {
        public int Id { get; set; }
        public Nullable<int> KayitId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Islem { get; set; }
        public Nullable<int> operation { get; set; }
        public Nullable<bool> Tipi { get; set; }
        public Nullable<bool> SehirDisi { get; set; }
        public string MusteriBİlgisi { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<System.DateTime> MusteriTipiDateTime { get; set; }
    
        public virtual KayitliPersonel KayitliPersonel { get; set; }
    }
}
