//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelTracking.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id { get; set; }
        public string IpAdress { get; set; }
        public string PcName { get; set; }
        public string MacAdress { get; set; }
        public string PageName { get; set; }
        public string Operation { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UserName { get; set; }
    }
}
