//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kod_Yazilim_Personel.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departman()
        {
            this.KayitliPersonel = new HashSet<KayitliPersonel>();
        }
    
        public int DepartmanID { get; set; }
        public string DepartmanName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KayitliPersonel> KayitliPersonel { get; set; }
        public virtual Departman Departman1 { get; set; }
        public virtual Departman Departman2 { get; set; }
    }
}
