//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kod_Yazilim_Personel.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayitliPersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KayitliPersonel()
        {
            this.Hareketler = new HashSet<Hareketler>();
            this.Notlar = new HashSet<Notlar>();
            this.Izinler = new HashSet<Izinler>();
        }
    
        public int KId { get; set; }
        public string KartID { get; set; }
        public string PAdSoyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string EPosta { get; set; }
        public string CepNum { get; set; }
        public string Adres { get; set; }
        public string FotoYol { get; set; }
        public Nullable<int> FingerID { get; set; }
        public Nullable<System.DateTime> IseBaslamaTarihi { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public Nullable<int> DepartmanID { get; set; }
        public string QRPath { get; set; }
        public string MobilePass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hareketler> Hareketler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notlar> Notlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izinler> Izinler { get; set; }
        public virtual Departman Departman { get; set; }
    }
}
